---
title: "R Notebook"
output: html_notebook
---

```{r check_interactive}

if(interactive()){
  print(date())
  print("This was run interactively. Please run with rmarkdown::render")
}else{
  print(paste0("This notebook was compiled on ", date()))
}
```


```{r load, message = F, results= 'hide'}
library(ggplot2)
library(dplyr)
library(monocle3)
library(here)
library(purrr)
library(tricycle)


```


```{r init}

teichman_mesenchymal_atlas_filename <- "/data/users/jared/atlas_processing/gut_cell_atlas/data/mesenchymal_gut.Rds"

cds <- readRDS(teichman_mesenchymal_atlas_filename)
```


```{r}
plot_cells(cds)

reducedDims(cds)

cds <- preprocess_cds(cds)
plot_pc_variance_explained(cds) 
```

```{r}
cds <- preprocess_cds(cds, num_dim = 30, verbose = T)

pData(cds)$sample_name <- pData(cds)[,"sample name"]
pData(cds)[,"sample name"] <- NULL
pData(cds)[,"Sample name"] <- NULL


#can't align on batch bc there are >150 batches, many have only a few cells in this subset
cds <- align_cds(cds, residual_model_formula_str = "~ sample_name + total_counts", verbose = T)

set.seed(152)
cds <- reduce_dimension(cds, cores = 8)
plot_cells(cds)
```

```{r}
assay(cds, "logcounts") <- normalized_counts(cds)

cds <- tricycle::project_cycle_space(cds, exprs_values = "logcounts")
  
#plot pca
p1 <- plot_cells(cds, reduction_method = "tricycleEmbedding") +
  labs(x = "Projected PC1", y = "Projected PC2") +
  ggtitle(sprintf("Projected cell cycle space (n=%d)",
                  ncol(cds))) + 
  theme_bw(base_size = 14)

cds <- estimate_cycle_position(cds)

#plot pca
p2 <- plot_cells(cds, reduction_method = "tricycleEmbedding", colour_by = "tricyclePosition") +
  labs(x = "Projected PC1", y = "Projected PC2") +
  ggtitle(sprintf("Projected cell cycle space (n=%d)",
                  ncol(cds))) + 
  theme_bw(base_size = 14)rownames(cds) <- fData(cds)[,"gene_id_trimmed"]

```

```{r}
#schwabe
cds <- estimate_cycle_stage(cds, gname.type = 'ENSEMBL', species = 'mouse', exprs_values = "logcounts")

plot_cells(cds, reduction_method = "tricycleEmbedding", colour_by = "CCStage") +
  labs(x = "Projected PC1", y = "Projected PC2") +
  ggtitle(sprintf("Projected cell cycle space (n=%d)",
                  ncol(cds))) +
  theme_bw(base_size = 14)

##cylic scale
p <- plot_emb_circle_scale(cds, dimred = 1, point.size = 3.5, point.alpha = 0.9) +
  theme_bw(base_size = 14)
legend <- circle_scale_legend(text.size = 5, alpha = 0.9)
p3 <- plot_grid(p, legend, ncol = 2, rel_widths = c(1, 0.4))

pca_emb_pos <- reducedDim(cds, "tricycleEmbedding")
tric_pos <- as.data.frame(colData(cds))[,"tricyclePosition"]

#Add back to cds object
reducedDim(cds, "tricycleEmbedding") <- pca_emb_pos
pData(cds)[,"tricyclePosition"] <- tric_pos

p<-plot_emb_circle_scale(cds, dimred = "UMAP", color_by = "tricyclePosition")
p4 <- plot_grid(p, legend, ncol = 2, rel_widths = c(1, 0.1))

print(p1)
print(p2)
print(p3)
print(p4)

```
