---
title: "Projection drivers"
output: html_document
---

```{r check_interactive}

if(interactive()){
  print(date())
  print("This was run interactively. Please run with rmarkdown::render")
}else{
  print(paste0("This notebook was compiled on ", date()))
}
```


```{r load, message = F, results= 'hide'}
library(projectR)
library(ggplot2)
library(dplyr)
library(monocle3)
library(here)
library(furrr)
library(cowplot)
library(purrr)
library(EMDomics)
source(here("scripts/accessory_functions/monocle_mods.R"))
source(here("scripts/accessory_functions/pattern_plotting.R"))
source(here("scripts/accessory_functions/patternFeatureCorrelationHeatmap.R"))
source(here("scripts/accessory_functions/convertHomologs.R"))


```


```{r init}
#declare patterns of interest
MENS_patterns <- c(16,27,32,41)
select_patterns <- c(MENS_patterns)

print(select_patterns)

###Load in projections ----
#teichman_gut_atlas_filename <- 
teichman_mesenchymal_atlas_filename <- "/data/users/jared/atlas_processing/gut_cell_atlas/data/mesenchymal_gut.Rds"

cds <- readRDS(teichman_mesenchymal_atlas_filename)

#Previously learned gene weights from NMF on logscaled expression counts
lmmp_6mo_patttern_geneweights_filename <- here("results/NMF/lmmp/old_pattern_run/50dims/pattern_gene_weights.csv")
learned_weights <- read.csv(
  file = lmmp_6mo_patttern_geneweights_filename,
  row.names = 1)

npattern <- dim(learned_weights)[2]

```
Gut atlas is human, patterns are defined in mouse, so convert genes to human
```{r}


homologs <- readRDS(here("teichman_gut_atlas/data/homologs.rds"))
# no_match <- tfs[!(tfs %in% homologs$Gene.name.human)]

#1 to 1 matches, NA if not present in dataset
matched_homologs <- convertHomologs(rownames(learned_weights), rownames(cds), homolog.table = homologs)
colnames(matched_homologs) <- c("mouse_gene_id","human_gene_id") 

matched_homologs_filt <- matched_homologs[!is.na(matched_homologs$human_gene_id),]

learned_weights_filt <- learned_weights[matched_homologs_filt$mouse_gene_id,]
rownames(learned_weights_filt) <- matched_homologs_filt$human_gene_id

#Now both are human genes, take intersection
genes_to_use <- intersect(rownames(learned_weights_filt), rownames(cds))

cds_filt <- cds[genes_to_use,]
learned_weights_filt <- learned_weights_filt[genes_to_use,]

# TODO: Why are 7k genes not matching
```
```{r}
plot_cells(cds)
coi <- c(20, 32, 34)

pairs <- list(c(20,32), c(32,34), c(20,34))
names(pairs) <- c("20 vs 32", "32 vs 34","20 vs 34")
```


```{r}
comp <- names(pairs)[1]

n_genes <- 500
min_effect_size <- log10(1.5)
n_gene_label <- 5

map(names(pairs), function(comp){
  
  print(comp)
  groups <- pairs[[comp]]
  
  c1 <- pData(cds) %>% as.data.frame() %>% filter(umap.clusters == groups[1]) %>% rownames()
  c2 <- pData(cds) %>% as.data.frame() %>% filter(umap.clusters == groups[2]) %>% rownames()

  proj_drivers <- projectionDriveR(assay(cds, "logcounts")[,c1],
                                   assay(cds, "logcounts")[,c2],
                                   loadings = learned_weights_filt,
                                   pattern_name = "cellPattern16")
  
  top_genes <- proj_drivers$normalized_weights %>%
    sort(decreasing = T) %>% .[1:n_genes] %>%
    names() %>%
    rev
  
  top_genes_filt <- proj_drivers$mean_ci[top_genes,] %>%
    mutate(mid = (high+low)/2) %>%
    arrange(mid) %>%
    filter(mid > min_effect_size | mid < -min_effect_size) %>% rownames()
  
  ci <- plotConfidenceIntervals(proj_drivers$mean_ci[top_genes,],
                          pattern_name = "cellPattern16",
                          sort = F,
                          genes = top_genes_filt, weights = proj_drivers$normalized_weights, weights_clip = .95)
  
  weighted_ci_lab <- proj_drivers$weighted_mean_ci[top_genes_filt,] %>% 
    mutate(mid = (high+low)/2) %>% mutate(label_name = NA_character_)

  idx <- c(1:n_gene_label, (dim(weighted_ci_lab)[1] - (n_gene_label-1)):dim(weighted_ci_lab)[1])
  
  weighted_ci_lab$label_name[idx] <- rownames(weighted_ci_lab)[idx]

  
  ci_wt <- plotConfidenceIntervals(weighted_ci_lab,
                          pattern_name = "cellPattern16",
                          sort = F,
                          genes = top_genes_filt, weights = proj_drivers$normalized_weights, weights_clip = .95)
  
  pl1 <- ci[[1]] + ggtitle(comp)
  pl2 <- ci[[3]]
  pl3 <- ci_wt[[1]] + ggtitle("") + xlab("Difference in weighted group means") + 
    theme(axis.title.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
    ggrepel::geom_label_repel(aes(label = label_name), max.overlaps = 20, force = 50)
  
  cowplot::plot_grid(pl1, pl2, pl3, ncol = 3, rel_widths = c(1,.5, 1), align ="h")

  
})
```

