---
title: "p20_analysis"
author: "Jared Slosberg"
date: "5/20/2022"
output: 
  html_document: 
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(monocle3)
library(tidyverse)

source(here("scripts/accessory_functions/monocle_mods.R"))
source(here("scripts/accessory_functions/pattern_plotting.R"))

```


```{r}
lmmp <- readRDS(here("TC_LMMP.rds"))
mens_name <- pData(lmmp) %>% as.data.frame() %>% filter(sample %in% c("p20", "p21")) %>%
  filter(cell_type == "MENs")
  
```

```{r}
plot_cells(lmmp)
plot_cells(lmmp[,pData(lmmp)$sample %in% c("p20", "p21")])
```


Subset to P20 and re-embed
```{r}
set.seed(122)

lmmp_p20 <- lmmp[,pData(lmmp)$sample %in% c("p20", "p21")]

lmmp_p20 <- preprocess_cds(lmmp_p20, num_dim = 50)
lmmp_p20 <- reduce_dimension(lmmp_p20, preprocess_method = "PCA", umap.fast_sgd = F)

#plot without batch correction
plot_cells(lmmp_p20, color_cells_by = "cell_type", group_label_size = 3)
plot_cells_mod(lmmp_p20, color_cells_by = "sample", group_label_size = 3) + facet_wrap(~sample)

#do batch correction and plot
lmmp_p20 <- align_cds(lmmp_p20, residual_model_formula_str = "~ batch + num_genes_expressed")
lmmp_p20 <- reduce_dimension(lmmp_p20, preprocess_method = "Aligned", umap.fast_sgd = F)
plot_cells_mod(lmmp_p20, color_cells_by = "sample", group_label_size = 3) + facet_wrap(~sample)


#Don't use batch correction because it is overcorrecting
lmmp_p20 <- reduce_dimension(lmmp_p20, preprocess_method = "PCA", umap.fast_sgd = F)
lmmp_p20 <- cluster_cells(lmmp_p20, 
                          "UMAP")

pData(lmmp_p20)$overall_clusters <- pData(lmmp_p20)$cluster
pData(lmmp_p20)$p20_clusters <- clusters(lmmp_p20)
 pData(lmmp_p20)$cluster <- NULL

plot_cells(lmmp_p20, color_cells_by = "overall_clusters", group_label_size = 3)
plot_cells(lmmp_p20, color_cells_by = "p20_clusters",group_label_size = 3)



```

Compare to previous annotations
```{r}
col_pal <- c('#E2B642','#E95939','#819E66','#B2BBE1','#ABD9E5','#9E7662','#D9A565',
             '#D1E539','#5BAEDE','#D748E2','#705ED7','#ED3B7B','#EBBBD0','#DA7DA7',
             '#81E83E','#DEE3AA','#6C6580','#6F908B','#E98E7E','#884EA5','#BAE8CF','#E1E2E1')

plot_cells(lmmp_p20, color_cells_by = "cell_type", group_label_size = 3)

ggplot(as.data.frame(pData(lmmp_p20)), aes(x = p20_clusters, fill = cell_type)) +
  geom_bar(position = "fill") + scale_fill_manual(values = col_pal)

ct_table <- as.data.frame.matrix(table(as.data.frame(pData(lmmp_p20))[, c("cell_type","p20_clusters")]))

ct_table
```
Take consensus annotations
```{r}
cls <- 1:dim(ct_table)[2]
cluster_annotations <- map_df(cls, function(cl){
  
  cts <- rownames(ct_table)
  
  ranks <- rank(-ct_table[,cl], ties = "first")
  primary_ind <- which(ranks ==1)
  sec_ind <- which(ranks ==2)
  
  primary_n <- ct_table[primary_ind, cl]
  primary_pct <- primary_n/sum(ct_table[,cl])
  primary_iden <- cts[primary_ind]
  
  sec_n <- ct_table[sec_ind, cl]
  sec_pct <- sec_n/sum(ct_table[,cl])  
  sec_iden <- cts[sec_ind]

  # 
  # as.data.frame(cl, primary_ind, primary_n, primary_pct)
  
  data.frame(p20_clusters = as.factor(cl), primary_identity = primary_iden, primary_pct,
             second_identity = sec_iden, sec_pct)

})

pData(lmmp_p20) <- pData(lmmp_p20) %>% as.data.frame() %>%
  tibble::rownames_to_column(var = "cell_id") %>%
  left_join(., cluster_annotations, by = "p20_clusters") %>%
  column_to_rownames(var = "cell_id") %>%
  DataFrame

plot_cells(lmmp_p20, color_cells_by = "primary_identity",group_label_size = 3)
 
cluster_annotations
```
Clean up annotations
```{r}
lmmp_p20 <- lmmp_p20[,!(pData(lmmp_p20)$primary_identity %in% c("unknown"))]
lmmp_p20 <- cluster_cells(lmmp_p20)


lmmp_p20$figure_celltype <- lmmp_p20$primary_identity %>%
  recode("NENs" = "NC-neurons",
         "Neuroglia" = "NC-glia", 
         "fibroblasts" = "Fibroblasts",
         "fibroblast 1" = "Fibroblasts",
         "ICC?" = "ICC",
         "smooth muscle or junk" = "SMC",
         "smooth muscle" = "SMC",
         "endothelial" = "Endothelial",
         "enterocytes" = "Enterocytes", 
         "macrophage" = "Macrophage", 
         "Unknown" = "Fibroblasts",
         "mucosal epithelium" = "Mucosal epith.")

plot_cells(lmmp_p20, color_cells_by = "figure_celltype")
```


Read in projected pattern weights (tc data into 6month patterns)
```{r}
sixmo_weights <- read.csv(here("results/6month_projection_weights/tc_in_6mo_LMMP_old_patterns.csv"), check.names = F)
colnames(sixmo_weights)[1] <- "cell_id"
colnames(sixmo_weights) <- colnames(sixmo_weights) %>% str_replace(., "6mo", "sixmo")

head(sixmo_weights)

pData(lmmp_p20) <- pData(lmmp_p20) %>% as.data.frame() %>% rownames_to_column(var = "cell_id") %>%
  left_join(., sixmo_weights, by = "cell_id") %>% column_to_rownames(var = "cell_id") %>% DataFrame


```
Plot MENs pattern usage
```{r}
pattern_wt_plots_select <- lapply(c(16, 27,32, 41), plotCellPatterns, cds_obj = lmmp_p20, do.clip = c(0.01,0.99), pattern_prefix = "sixmo_cellPattern")
pattern_wt_plots_select
```
```{r}
saveRDS(lmmp_p20, here("tc_lmmp_p20.rds"))
```

