---
title: "Make h5ad for scVelo"
output: html_notebook
---

```{r, message=F}
library(here)
library(monocle3)
library(zellkonverter)
library(purrr)
library(tidyverse)
library(glue)
library(Matrix)
```
Load existing monocle3 object, and read in spliced counts for matched cells

```{r}
cds <- readRDS(here("6mo_MENS_11-25.rds"))

plot_cells(cds, color_cells_by = "cycle_phase") #not expecting much for velocity based on no cycling cells

```

```{r}
spliced_status <- c("s","u") #names of files from kallisto
spliced_status_full <- c("spliced","unspliced")
samples <- c("TH","TL")
kallisto_out_path <- here("preprocessing/bus_output")


exprs_mat_list <- pmap(list(spliced_status, spliced_status_full), function(spl, spl_full){

  #loop over each sample and read in spliced and unspliced matrices
  exprs_mat_sep <- map(samples, function(samp){
    
    kall_path <- glue("{kallisto_out_path}/{samp}/{spl_full}")
    print(kall_path)
   
    
    mtx <- t(readMM(glue("{kall_path}/{spl}.mtx")))
    
    #character vector
    genes <- read_delim(glue("{kall_path}/{spl}.genes.txt"), delim = "\n", col_names = F) %>%
      pull(1)
    
    #read in cells and append .{sample} so they match cell data set
    cells <- read_delim(glue("{kall_path}/{spl}.barcodes.txt"), delim = "\n", col_names = F) %>%
      pull(1) %>% 
      paste(.,samp, sep = ".")
    
    cells
    cells_filt <- cells[cells %in% colnames(cds)]
    
    colnames(mtx) <- cells
    rownames(mtx) <- genes
    
    mtx_filt <- mtx[,cells_filt]
    
  })
  
  #merged
  exprs_mat <- do.call(Matrix::cbind2, exprs_mat_sep)

})
names(exprs_mat_list) <- spliced_status_full

assay(cds, "unspliced") <- exprs_mat_list[["unspliced"]]
assay(cds, "spliced") <- exprs_mat_list[["spliced"]]

```

```{r}
#works on sce and cds
writeH5AD(cds, file = here("6mo_MENS_11-25.h5ad"), X_name = "counts")
```

