---
title: "scDRS set up"
output: html_notebook
---

Before running scDRS - make a covariates file and write to .h5ad AnnData format

```{r, message=FALSE, results = 'hide'}
library(monocle3)
library(ggplot2)
library(tidyverse)
library(here)
library(zellkonverter)

```

```{r}
lmmp <- readRDS(here("6month_LMMP.rds"))

```

```{r}
#Variables to regress out must be numeric

pData(lmmp) <- pData(lmmp) %>%
  as.data.frame() %>% 
  mutate(batch_recode =
           case_when(
             batch == "TH" ~ 0,
             batch == "TL" ~ 1)) %>%
  DataFrame()
           


covar_use <- c("batch_recode", "num_genes_expressed")
covar <- pData(lmmp)[,covar_use] %>% as.data.frame() %>% tibble::rownames_to_column(var = "index")

write_tsv(covar, here("DRS/data/lmmp_covar.tsv"))

```

Write to h5ad
```{r}

#homolog matching for gene sets is based on gene symbols (short name)
rownames(lmmp) <- fData(lmmp)$gene_short_name

zellkonverter::writeH5AD(lmmp, file = here("6month_LMMP.h5ad"), skip_assays = FALSE)
```

